// app/src/components/celebration/registry.ts
import type { MilestoneConfig } from './types'
import { GRADUATION } from './achievements/graduation'
import {
  STREAK_3, STREAK_7, STREAK_14, STREAK_30, STREAK_LOST, STREAK_REVIVED,
} from './configs/streak-milestones'
import {
  BADGE_CONSISTENCY_SEED, BADGE_CONSISTENCY_SAPLING, BADGE_CONSISTENCY_OAK,
  BADGE_EFFORT_SEED, BADGE_EFFORT_SAPLING, BADGE_EFFORT_OAK,
} from './configs/badge-effort-consistency'
import {
  BADGE_SAVER_SEED, BADGE_SAVER_SAPLING, BADGE_SAVER_OAK,
  BADGE_SCHOLAR_SEED, BADGE_SCHOLAR_SAPLING, BADGE_SCHOLAR_OAK,
  BADGE_LANDMARK_SEED, BADGE_LANDMARK_SAPLING, BADGE_LANDMARK_OAK,
} from './configs/badge-saver-scholar-landmark'

export const CONFIGS: Record<string, MilestoneConfig> = {
  GRADUATION,
  STREAK_3, STREAK_7, STREAK_14, STREAK_30, STREAK_LOST, STREAK_REVIVED,
  BADGE_CONSISTENCY_SEED, BADGE_CONSISTENCY_SAPLING, BADGE_CONSISTENCY_OAK,
  BADGE_EFFORT_SEED, BADGE_EFFORT_SAPLING, BADGE_EFFORT_OAK,
  BADGE_SAVER_SEED, BADGE_SAVER_SAPLING, BADGE_SAVER_OAK,
  BADGE_SCHOLAR_SEED, BADGE_SCHOLAR_SAPLING, BADGE_SCHOLAR_OAK,
  BADGE_LANDMARK_SEED, BADGE_LANDMARK_SAPLING, BADGE_LANDMARK_OAK,
}
